# Generated by Django 5.1.6 on 2025-03-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100)),
                ('short_youtube_demonstration', models.URLField(blank=True, max_length=500)),
                ('in_depth_youtube_explanation', models.URLField(blank=True, max_length=500)),
                ('difficulty_level', models.CharField(max_length=50)),
                ('target_muscle_group', models.CharField(max_length=100)),
                ('prime_mover_muscle', models.CharField(blank=True, max_length=100)),
                ('secondary_muscle', models.CharField(blank=True, max_length=100)),
                ('tertiary_muscle', models.CharField(blank=True, max_length=100)),
                ('primary_equipment', models.CharField(max_length=100)),
                ('primary_items', models.PositiveIntegerField(default=0)),
                ('secondary_equipment', models.CharField(blank=True, max_length=100)),
                ('secondary_items', models.PositiveIntegerField(default=0)),
                ('posture', models.CharField(max_length=50)),
                ('single_or_double_arm', models.CharField(max_length=50)),
                ('continuous_or_alternating_arms', models.CharField(max_length=50)),
                ('grip', models.CharField(max_length=50)),
                ('load_position_ending', models.CharField(blank=True, max_length=100)),
                ('continuous_or_alternating_legs', models.CharField(max_length=50)),
                ('foot_elevation', models.CharField(max_length=50)),
                ('combination_exercises', models.CharField(max_length=100)),
                ('movement_pattern_1', models.CharField(max_length=100)),
                ('movement_pattern_2', models.CharField(blank=True, max_length=100)),
                ('movement_pattern_3', models.CharField(blank=True, max_length=100)),
                ('plane_of_motion_1', models.CharField(max_length=50)),
                ('plane_of_motion_2', models.CharField(blank=True, max_length=50)),
                ('plane_of_motion_3', models.CharField(blank=True, max_length=50)),
                ('body_region', models.CharField(max_length=50)),
                ('force_type', models.CharField(max_length=50)),
                ('mechanics', models.CharField(max_length=50)),
                ('laterality', models.CharField(max_length=50)),
                ('primary_exercise_classification', models.CharField(max_length=100)),
            ],
        ),
    ]
