# Generated by Django 5.2 on 2025-04-23 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_player'),
        ('workout', '0004_routineimprovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineimprovement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.player'),
        ),
        migrations.AlterField(
            model_name='workoutprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.player'),
        ),
    ]
