# Generated by Django 5.2 on 2025-04-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_basketballdrill_basketballworkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealGameDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('situation_type', models.CharField(choices=[('Fast Break', 'Fast Break'), ('Pick and Roll', 'Pick and Roll'), ('Isolation', 'Isolation'), ('Transition Defense', 'Transition Defense'), ('Inbound Plays', 'Inbound Plays'), ('Zone Offense', 'Zone Offense'), ('Zone Defense', 'Zone Defense'), ('Press Break', 'Press Break'), ('End Game', 'End Game'), ('All', 'All Situations')], max_length=50)),
                ('description', models.TextField()),
                ('video_link', models.URLField(max_length=500)),
                ('duration_min', models.PositiveIntegerField()),
            ],
        ),
    ]
