# Generated by Django 5.2 on 2025-04-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_realgamedrill'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealGameDrillWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('situation_type', models.CharField(max_length=100)),
                ('drills', models.ManyToManyField(to='workout.realgamedrill')),
            ],
        ),
    ]
