# Generated by Django 5.1.6 on 2025-05-14 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_player'),
        ('workout', '0008_realgamedrillworkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('equipment_needed', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercises', models.ManyToManyField(to='workout.recoveryexercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.player')),
            ],
        ),
    ]
