# Generated by Django 5.1.6 on 2025-05-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0009_recoveryexercise_recoveryplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoveryplan',
            name='created_at',
        ),
    ]
