# Generated by Django 5.1.6 on 2025-05-14 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0010_remove_recoveryplan_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recoveryexercise',
            old_name='name',
            new_name='exercise_name',
        ),
    ]
