# Generated by Django 5.1.6 on 2025-03-16 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='player',
        ),
    ]
